name: Deploy DNS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  LOCATION: westus
  PRIMARY_DNS_ZONE: ppanda.org
  RESOURCE_GROUP_NAME: rg-edge-pub-westus

jobs:
  deploy-dns:
    name: DNS Deployment
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Login to Azure using a service principal stored in GitHub Secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run the DNS deployment script (PowerShell Core)
      - name: Deploy DNS
        run: |
          ./deploy-dns.sh \
            "${{ env.RESOURCE_GROUP_NAME }}" \
            "${{ env.LOCATION }}" \
            "${{ env.PRIMARY_DNS_ZONE }}"
        shell: bash
