name: Deploy Edge VM

on:
  push:
    branches:
      - main
    paths:
      - modules/edge-vm/**
  pull_request:
    branches:
      - '**'
    paths:
      - modules/edge-vm/**

env:
  RESOURCE_GROUP: rg-edge-pub-westus
  TEMPLATE_FILE: ./modules/edge-vm/main.bicep

jobs:
  deploy-edge-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_VM }}

      - name: Edge VM Deployment Dry Run
        if: github.event_name == 'pull_request'
        run: |
          az deployment group what-if \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --template-file "${{ env.TEMPLATE_FILE }}" \
            --parameters ssh_public_key="${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Edge VM Deployment
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          az deployment group create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --template-file "${{ env.TEMPLATE_FILE }}" \
            --parameters ssh_public_key="${{ secrets.SSH_PUBLIC_KEY }}"
